#!/bin/bash
# /etc/init.d/qbchatbot

### BEGIN INIT INFO
# Provides:          qbchatbot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       This service is used to manage the q-municate chat xmpp bot
### END INIT INFO

case "$1" in
    start)
        echo "Starting qb chat bot"
        node /home/pi/chat_bots-sdk/examples/echo_one_to_one_bot/echo_one_to_one_bot.js &
        ;;
    stop)
        echo "Stopping qb chat bot"
        sudo pkill -f qbchatbot
        ;;
    *)
        echo "Usage: /etc/init.d/qbchatbot start|stop"
        exit 1
        ;;
esac

exit 0
